version: '3.8'

services:
  smart-todo-manager:
    build: .
    container_name: smart-todo-manager
    restart: unless-stopped
    
    # Mount project directory for file watching
    volumes:
      - ../../:/project:ro
      - ./data:/app/.todo-data
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - PROJECT_ROOT=/project
    
    # Port mapping for health checks
    ports:
      - "3001:3001"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - smart-todo-network

networks:
  smart-todo-network:
    driver: bridge

volumes:
  smart-todo-data:
    driver: local