# AlertManager Configuration for Spontra Platform

global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@spontra.com'
  smtp_auth_username: 'alerts@spontra.com'
  smtp_auth_password: 'your-email-password'
  smtp_require_tls: true

  # Slack configuration
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

  # Global alert resolve timeout
  resolve_timeout: 5m

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert distribution
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  
  routes:
    # Critical system alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 15m
      
    # Infrastructure team alerts
    - match:
        team: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 30s
      
    # Backend team alerts
    - match:
        team: backend
      receiver: 'backend-team'
      group_interval: 30s
      
    # Database team alerts
    - match:
        team: database
      receiver: 'database-team'
      group_interval: 1m
      
    # Security alerts
    - match:
        team: security
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 30m
      
    # Business/Product alerts
    - match:
        team: product
      receiver: 'product-team'
      group_interval: 5m
      repeat_interval: 4h

# Alert receivers configuration
receivers:
  # Default webhook
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@spontra.com'
        subject: '🚨 CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        html: |
          <h2>🚨 Critical Alert</h2>
          {{ range .Alerts }}
          <p><strong>{{ .Annotations.summary }}</strong></p>
          <p>{{ .Annotations.description }}</p>
          <p>Service: {{ .Labels.service }} | Instance: {{ .Labels.instance }}</p>
          <p>Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          {{ end }}
    slack_configs:
      - channel: '#alerts-critical'
        title: '🚨 Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ end }}'
        send_resolved: true

  # Infrastructure team
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@spontra.com'
        subject: '⚠️ Infrastructure Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}
    slack_configs:
      - channel: '#infrastructure'
        title: '⚠️ Infrastructure Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Backend team
  - name: 'backend-team'
    email_configs:
      - to: 'backend@spontra.com'
        subject: '🔧 Backend Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    slack_configs:
      - channel: '#backend'
        title: '🔧 Backend Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Database team
  - name: 'database-team'
    email_configs:
      - to: 'database@spontra.com'
        subject: '🗄️ Database Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    slack_configs:
      - channel: '#database'
        title: '🗄️ Database Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Security team
  - name: 'security-team'
    email_configs:
      - to: 'security@spontra.com'
        subject: '🛡️ Security Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          SECURITY ALERT - Immediate attention required
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    slack_configs:
      - channel: '#security'
        title: '🛡️ Security Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ end }}'
        color: 'danger'

  # Product team
  - name: 'product-team'
    email_configs:
      - to: 'product@spontra.com'
        subject: '📊 Product Metrics Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    slack_configs:
      - channel: '#product'
        title: '📊 Product Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

# Inhibition rules to reduce noise
inhibit_rules:
  # Inhibit warning alerts if critical alerts are firing for the same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'instance']

  # Inhibit service alerts if the instance is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service', 'instance']

  # Inhibit high error rate alerts if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighErrorRate'
    equal: ['service']

# Silencing configuration
silencing:
  # Default silence duration
  default_silence_duration: 1h
  
  # Maximum silence duration
  max_silence_duration: 24h