apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  redis-host: "REDIS_HOST_PLACEHOLDER"
  redis-port: "6379"
  elasticsearch-url: "http://elasticsearch:9200"
  kafka-brokers: "kafka:9092"
  bigquery-dataset: "spontra_dev_analytics"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream user-service {
        server user-service:80;
    }
    
    upstream search-service {
        server search-service:80;
    }
    
    upstream pricing-service {
        server pricing-service:80;
    }
    
    upstream data-ingestion-service {
        server data-ingestion-service:80;
    }
    
    upstream frontend {
        server frontend:80;
    }
    
    server {
        listen 80;
        
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/auth/ {
            proxy_pass http://user-service/api/v1/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/users/ {
            proxy_pass http://user-service/api/v1/users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/search/ {
            proxy_pass http://search-service/api/v1/search/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Destination exploration (search-service proxies to data-ingestion-service)
        location /api/v1/explore/ {
            proxy_pass http://search-service/api/v1/explore/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Destination data
        location /api/v1/destinations/ {
            proxy_pass http://search-service/api/v1/destinations/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/pricing/ {
            proxy_pass http://pricing-service/api/v1/pricing/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/ingestion/ {
            proxy_pass http://data-ingestion-service/api/v1/ingestion/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }