apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
    service: search-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      serviceAccountName: search-service
      containers:
      - name: search-service
        image: gcr.io/PROJECT_ID/search-service:IMAGE_TAG
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "search_service_db"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis-host
        - name: ELASTICSEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: elasticsearch-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-instances=PROJECT_ID:us-central1:spontra-dev-postgres=tcp:5432"
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-service
  annotations:
    iam.gke.io/gcp-service-account: spontra-dev-services@PROJECT_ID.iam.gserviceaccount.com