global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
    metrics_path: '/metrics'

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8081']
    metrics_path: '/metrics'

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:8082']
    metrics_path: '/metrics'

  - job_name: 'data-ingestion-service'
    static_configs:
      - targets: ['data-ingestion-service:8083']
    metrics_path: '/metrics'

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']